### PR TITLE
Proposition: Change configuration source from env vars to toml file

### PR DESCRIPTION
**Pull request by marcofiset**
Environment variables + Direnv combo is a nice way to configure applications. However it comes with a pretty big drawback: you _must_ be `cd`'d in the application's directory for your env vars to be loaded by direnv.

I would like to run `yanky` from anywhere in my CLI. However, I can't just set it in my `PATH`, because Direnv won't load my environment variables.

That's why I'm suggesting these changes: moving from env vars to a TOML config file. The config file lives alongside the executable, and is read at startup. It will always work, regardless of your current directory.

There were also some formatting issues according to my language server 🤷🏻‍♂️

### CODE REVIEW

**Comment by marcofiset** [comment]
If you decide this is a good idea, I'll go ahead and rewrite the portion of the README regarding configuration.

**Comment by marcofiset** [comment]
And if you think this isn't a good idea, I'll go rogue and continue using this branch for my installation 😄

**Comment by GregLMcDonald** [comment]
I think is a great idea and love the self-itch-scratching thing we've got going on here. Not sure what I'm doing wrong. I pulled the branch, setup my config.toml and _in the directory_ if I call `./yanky` it works, but if I add <path to yanky repo> to my PATH, it just fails silently. Any idea why?

**Comment by marcofiset** [comment]
Ah! My bad. I'm not using the PATH at all. I thought I was, but I actually setup a shell function to invoke yanky (I'm using the fish shell):

```fish
function yanky
  pushd ~/work/yanky
  ./yanky
  popd
end
```

That was not working with direnv.

**Review by GregLMcDonald — APPROVED** [review]

**Pull request merged**
